baseURL = 'http://www.cailegacy.net/'
theme = 'PaperMod'

enableEmoji = true

defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh]
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '中文'
    title = '欣欣向荣'
    weight = 1
    [languages.zh.menu]
      [[languages.zh.menu.main]]
      name = "关于"
      pageRef = "/about"
      weight = 30
      [[languages.zh.menu.main]]
      name = '致谢'
      pageRef = '/acknowledgement'
      weight = 25
      [[languages.zh.menu.main]]
      name = '家谱'
      pageRef = '/family-tree'
      weight = 20
      [[languages.zh.menu.main]]
      name = '影像'
      pageRef = '/photos'
      weight = 10
      [[languages.zh.menu.main]]
        name = '文章'
        pageRef = '/posts'
        weight = 5
    [languages.zh.params]
      author = '蔡氏家族'
      description = '谨以此网站纪念蔡向荣，赵欣以及其他逝去的亲人们。'
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Xin and Xiangrong'
    weight = 2
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
        weight = 30
      [[languages.en.menu.main]]
      name = 'Acknowledgement'
      pageRef = '/acknowledgement'
      weight = 25
      [[languages.en.menu.main]]
        name = 'Family Tree'
        pageRef = '/family-tree'
        weight = 20
      [[languages.en.menu.main]]
        name = 'Photos'
        pageRef = '/photos'
        weight = 10
      [[languages.en.menu.main]]
        name = 'Posts'
        pageRef = '/posts'
        weight = 5
    [languages.en.params]
      author = 'Cai Family'
      description = 'This website is dedicated to the memory of Zhao Xin (赵欣) and Cai Xiangrong (蔡向荣) and other family members who have left us.'

[params]
  # PaperMod
  ShowShareButtons = true

  # header social icons
  mastodon = 'https://ieji.de/@cailegacy'   # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon
  github = 'xinxinxiangrong-family'         # github.com/YOUR_GITHUB_ID

